const productList = [
    {
        name: 'Bike',
        price: 120,
        image:'https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        description:'Es una computadora......',
    },
    {
        name: 'Pantalla',
        price: 220,
        image: 'https://www.soriana.com/dw/image/v2/BGBD_PRD/on/demandware.static/-/Sites-soriana-grocery-master-catalog/default/dwe2d879f8/images/product/7502238270390_A.jpg?sw=1000&sh=1000&sm=fit',
        description:'Es una computadora......',
      },
      {
        name: 'Compu',
        price: 620,
        image: 'https://res.cloudinary.com/walmart-labs/image/upload/w_960,dpr_auto,f_auto,q_auto:best/mg/images/categorias/d-computo/f-computo-de-escritorio.jpg',
        description:'Es una computadora......',
      },
      {
        name: 'Mouse',
        price: 120,
        image: 'https://images.pexels.com/photos/6804455/pexels-photo-6804455.jpeg?auto=compress&cs=tinysrgb&w=600',
        description:'Es una computadora......',
    },
    {
        name: 'Desktop',
        price: 220,
        image: 'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=600',
        description:'Es una computadora......',
      },
      {
        name: 'Teclado',
        price: 620,
        image: 'https://images.pexels.com/photos/1194713/pexels-photo-1194713.jpeg?auto=compress&cs=tinysrgb&w=600',
        description:'Es una computadora......',
      },
      {
        name: 'Pantallas',
        price: 1220,
        image:'https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg?auto=compress&cs=tinysrgb&w=600',
        description:'Es una computadora......',
    },
    {
        name: 'Laptop',
        price: 2200,
        image: 'https://images.pexels.com/photos/2528118/pexels-photo-2528118.jpeg?auto=compress&cs=tinysrgb&w=600',
        description:'Es una computadora......',
      },
      {
        name: 'Teclado y mouse',
        price: 620,
        image: 'https://images.pexels.com/photos/1714205/pexels-photo-1714205.jpeg?auto=compress&cs=tinysrgb&w=600',
        description:'Es una computadora......',
      },
      {
        name: 'Teclado',
        price: 120,
        image:'https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description:'Es una computadora......',
    },
    {
        name: 'CPU',
        price: 220,
        image: 'https://images.pexels.com/photos/2399840/pexels-photo-2399840.jpeg?auto=compress&cs=tinysrgb&w=600',
        description:'Es una computadora......',
      },
      {
        name: 'Phone',
        price: 620,
        image: 'https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description:'Es una computadora......',
      },
      {
        name: 'headphones',
        price: 120,
        image:'https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description:'Es una computadora......',
    },
    {
        name: 'headphones + microphone',
        price: 220,
        image: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=600',
        description:'Es una computadora......',
      },
      {
        name: 'Gaming Chair',
        price: 620,
        image: 'https://ddtech.mx/assets/uploads/25898ffe57291f6fc1af2c9fad4bbcf6.jpg',
        description:'Es una computadora......',
      },
];
